default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.7.0"
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
